# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: publish-to-xxx

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version-file: ".nvmrc"
  #     - run: npm ci
  #     #     - run: npm test
  #     - run: npm run build
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: output
  #         path: |
  #           dist

  publish-npm:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/
      # - uses: actions/download-artifact@v3
      #   with:
      #     name: output
      #     path: |
      #       dist
      # - run: npm ci
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
